85 guidance on how to use themes
joonaruutiainen/interactive-process-graphs pull request #106
Opened 2021-12-07 14:02 UTC by helmikerttu

Closes #85

2021-12-07 14:06 UTC, vade123 requested changes

2021-12-07 14:06 UTC, vade123 commented on README.md
> +and backgorund color is for the background of the canvas.
please fix typing error

2021-12-07 14:19 UTC, joonaruutiainen approved these changes

2021-12-07 14:20 UTC, vade123 submitted a review, later dismissed

2021-12-10 10:18 UTC, joonaruutiainen approved these changes

2021-12-10 10:20 UTC, vade123 approved these changes

2021-12-10 10:20 UTC, merged