Info component #55
joonaruutiainen/interactive-process-graphs pull request #76
Opened 2021-11-17 11:46 UTC by Tumpbe

2021-11-17 12:46 UTC, vade123 approved these changes

2021-11-17 12:48 UTC, vade123 requested changes

2021-11-17 12:48 UTC, vade123 commented on src/components/ProcessGraph.tsx
> +
Could just use `setInfoVisible(false)` directly instead of wrapping it into a function that does not do anything else

2021-11-20 13:27 UTC, vade123 commented on src/components/InfoBox.tsx
> +  border-radius: 15px;
use theme now that its merged to main

2021-11-23 15:25 UTC, joonaruutiainen commented on src/components/InfoBox.tsx
> +  border-radius: 15px;
@Tumpbe tämä edelleen

2021-11-24 10:14 UTC, joonaruutiainen approved these changes

2021-11-24 10:14 UTC, vade123 approved these changes

2021-11-24 10:14 UTC, merged